database:
  host: lbnl-btm-drl.lbl.gov
  port: 9003
  username: hil_flexlab
  password: h!l2021da+a$tore
  database: hil

  setpoint_table:

query_condition:
    1a:
        plugload:
            variables: [desk1_plug_power, desk2_plug_power, desk3_plug_power, desk4_plug_power, desk5_plug_power, desk6_plug_power,
             desk3_light_power, desk4_light_power, desk2_light_power, desk1_6_light_power, desk5_light_power]
            agg: mean
            table: cell_lighting_plug_1a


        temp:
            variables: [1A-VAV1-Zn_Temp, 1A-VAV2-Zn_Temp, 1A-VAV3-Zn_Temp]
            agg: last
            table: cell_vav_1a

        temp_sp:
            variables: [1A-VAV1-OccupiedCoolingSetpt, 1A-VAV1-UnoccupiedCoolingSetpt, 1A-VAV1-OccupiedHeatingSetpt,
             1A-VAV1-UnoccupiedHeatingSetpt, 1A-VAV2-OccupiedCoolingSetpt, 1A-VAV2-UnoccupiedHeatingSetpt, 1A-VAV2-UnoccupiedCoolingSetpt,
             1A-VAV2-OccupiedHeatingSetpt, 1A-VAV3-OccupiedCoolingSetpt, 1A-VAV3-UnoccupiedHeatingSetpt, 1A-VAV3-UnoccupiedCoolingSetpt,
             1A-VAV3-OccupiedHeatingSetpt]
            agg: last
            table: cell_vav_1a

        demand:
            variables: [1A-El-AHU, 1A-El-CHWP, 1A-El-HWP, 1A-El-Exhaust Fan, 1A-Th-Chilled Water]
            agg: mean
            table: processed_cell_1a

        weather:
            variables: [1B-OAT-1]
            agg: last
            table: cell_hvac_1b

        weather_1:
            variables: [1A-MidZone-TCS6-DBT, 1A-NorthZone-DBT, 1A-WindowZone-TCS7-DBT]
            agg: last
            table: cell_thermalstation_1ab

        discharge_air_temp:
            variables: [1A-VAV1-DischargeAirTemp, 1A-VAV2-DischargeAirTemp, 1A-VAV3-DischargeAirTemp, 1A-VAV1-DischargeAirflow,
            1A-VAV2-DischargeAirflow, 1A-VAV3-DischargeAirflow]
            agg: last
            table: cell_vav_1a

        airflow:
            variables: [1A-ASAM-1, 1A-ARAM-1, 1A-SAT-1, 1A-OADA-1-POSN, 1A-RADA-1-POSN]
            agg: mean
            table: cell_hvac_1a

        strat_tree:
            variables: [1a_strat_window_bottom, 1a_strat_window_middle, 1a_strat_window_top]
            agg: mean
            table: pcm_data

    1b:
        plugload:
            variables: [desk3_light_power, desk1_light_power, desk5_light_power, desk2_light_power, desk6_light_power, desk4_light_power,
             desk1_plug_power, desk2_plug_power, desk3_plug_power, desk4_plug_power, desk5_plug_power, desk6_plug_power]
            agg: mean
            table: cell_lighting_plug_1b


        temp:
            variables: [1B-VAV1-Zn_Temp, 1B-VAV2-Zn_Temp, 1B-VAV3-Zn_Temp]
            agg: last
            table: cell_vav_1b

        temp_sp:
            variables: [1B-VAV1-OccupiedCoolingSetpt, 1B-VAV1-UnoccupiedCoolingSetpt, 1B-VAV1-OccupiedHeatingSetpt,
             1B-VAV1-UnoccupiedHeatingSetpt, 1B-VAV2-OccupiedCoolingSetpt, 1B-VAV2-UnoccupiedHeatingSetpt, 1B-VAV2-UnoccupiedCoolingSetpt,
             1B-VAV2-OccupiedHeatingSetpt, 1B-VAV3-OccupiedCoolingSetpt, 1B-VAV3-UnoccupiedHeatingSetpt, 1B-VAV3-UnoccupiedCoolingSetpt,
             1B-VAV3-OccupiedHeatingSetpt]
            agg: last
            table: cell_vav_1b

        demand:
            variables: [1B-El-AHU, 1B-El-CHWP, 1B-El-Exhaust Fan, 1B-El-HWP,1B-Th-Chilled Water]
            agg: mean
            table: processed_cell_1b


        weather:
            variables: [1B-OAT-1]
            agg: last
            table: cell_hvac_1b

        weather_1:
            variables: [1B-MidZone-TCS9-DBT, 1B-NorthZone-DBT, 1B-WindowZone-TCS10-DBT]
            agg: last
            table: cell_thermalstation_1ab

        discharge_air_temp:
            variables: [1B-VAV1-DischargeAirTemp, 1B-VAV2-DischargeAirTemp, 1B-VAV3-DischargeAirTemp, 1B-VAV1-DischargeAirflow,
            1B-VAV2-DischargeAirflow, 1B-VAV3-DischargeAirflow]
            agg: last
            table: cell_vav_1b

        airflow:
            variables: [1B-ASAM-1, 1B-ARAM-1, 1B-SAT-1, 1B-OADA-1-POSN, 1B-RADA-1-POSN]
            agg: mean
            table: cell_hvac_1b

        strat_tree:
            variables: [1b_strat_window_bottom, 1b_strat_window_middle, 1b_strat_window_top, 1b_strat_core_middle, 1b_strat_core_top, 1b_strat_door_bottom, 1b_strat_door_middle, 1b_strat_door_top]
            agg: mean
            table: pcm_data

        pcm:
            variables: [1b_desk3_door_right_ceiling, 1b_desk3_door_right_plenum, 1b_desk4_door_left_ceiling, 1b_desk4_door_left_plenum, 1b_desk1_window_right_ceiling, 1b_desk1_window_right_plenum, 1b_desk6_window_left_ceiling, 1b_desk6_window_left_plenum, 1b_window_middle_ceiling, 1b_window_middle_plenum, 1b_desk2_core_right_ceiling, 1b_desk2_core_right_plenum, 1b_desk5_core_left_ceiling, 1b_desk5_core_left_plenum]
            agg: mean
            table: pcm_data