modbus:
    UNIT_ID: 0
    modbus_type: tcp #tcp #serial
    ip: 192.168.92.105
    port: 502
    enable_logging: True

    ### below configuration is if we are serial
    #serial_port: /dev/cu.usbserial-14620
    #method: rtu
    #stopbits: 1
    #bytesize: 8
    #parity: N
    #baudrate: 9600

    byte_order: big
    word_order: little

    OFFSET_REGISTERS: 1

    discrete_registers: {}
      # islanding_state: [0x1000]
      # island_type: [0x1001]
      # bess_availability: [0x1002]
      # pge_state: [0x1003]
      # pcc_breaker_state: [0x1004]
      # bess_pv_breaker_state: [0x1005]

    coil_registers: {}
    input_registers: {}

    holding_registers:
      temperature_setpoint1: [1, 16int]
      temperature_setpoint2: [2, 16int]
      temperature_high_alarm: [3, 16int]
      temperature_low_alarm: [4, 16int]

      heartbeat: [15, 16int]
      zone1_temp: [17, 8int]
      zone4_temp: [20, 8int]
      zone1_status: [23, 16int]
      zone4_status: [26, 16int]
      # heartbeat: [0x4000, 16uint]
      # real_power_setpoint: [0x4002, 32int]
      # reactive_power_setpoint: [0x4004, 32int]
      # target_real_power: [0x4006, 32int]
      # target_reactive_power: [0x4008, 32int]
      # battery_total_capacity: [0x400A, 32int]
      # battery_current_stored_energy: [0x400C, 32int]
      # total_actual_real_power: [0x400E, 32int]
      # total_actual_reactive_power: [0x4010, 32int]
      # total_actual_apparent_power: [0x4012, 32int]
      # #active_power_output_limit: [0x4014, 32uint]
      # current_power_production: [0x4016, 32float]
      # ac_current_phase_a: [0x4018, 32float]
      # ac_current_phase_b: [0x401A, 32float]
      # ac_current_phase_c: [0x401C, 32float]
      # ac_voltage_ab: [0x401E, 32float]
      # ac_voltage_bc: [0x4020, 32float]
      # ac_voltage_ca: [0x4022, 32float]
      # ac_frequency: [0x4024, 32float]
      # fault_condition: [0x402A, 32uint]
      # pge_voltage: [0x4026, 32float]
      # pge_frequency: [0x4028, 32float]
      # microgrid_voltage: [0x402C, 32float]


#press select button -> cycle through configuration
#-> protocol: rtu
#-> adr: 0--> set it to 1  // use up and down arrows
#-> rat: 9600

# controller does serial to modbus bridge
#repairs@advantageelectronics.com